-- 20260710173500_cleanup_garbage_tasks.sql
BEGIN;

-- Delete all communication tasks that were automatically generated by the previous migration
-- and restored by the rollback, which have title 'Продзвон' and comment 'Нагадування клієнту перед виїздом' or 'Нове замовлення' etc.
DELETE FROM public.communication_tasks 
WHERE title IN ('Продзвон', 'Активність');

COMMIT;
